### ISSUE TITLE
Question: Does this work with YAGO?

### ISSUE THREAD

**Issue by lastzero** [shful/gofp#1]
Sorry for abusing the project issues for asking a question! I didn't find any other way to contact you.

I'm the maintainer of @photoprism and we need a compact ontology to improve our search. If you search for fish, you should also find sharks. Same for NYC and New York etc...

It seems like [YAGO](https://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/yago/downloads/) is a good starting point. Obviously we need to parse the files and reduce the amount of data for our use case (image classification). Can we use `gofp` for this? If yes: What specific YAGO files / themes do we need to download? Can you give us an example?

I hope you see this... Thank you very much and sorry again 😃

**Comment by shful** [comment]
Gofp, as I expect, needs further completion to fully parse YAGO. You also need an OWL-functional representation.
The size of YAGO might be handled by replacing the default implementation of the Gofp store.AxiomStore interface. This decides how to store axioms, and if at all. The parser calls the "Store*" functions with each single axiom parsed -- thats a "Visitor" pattern -- and you decide to keep or discard each one.
Feel also free to mail me at: shful2019b3 at example.org with example=posteo.

**Comment by lastzero** [comment]
@shful Thank you! We've decided to manually define related terms for now as there are only 1000 different labels. We might come back to this later, when we have more time.
